<template>
  <div class="app-container">
    <p class="warn-content">
      {{ $t('guide.description') }}
      <a href="https://github.com/kamranahmedse/driver.js" target="_blank">driver.js.
      </a>
    </p>
    <el-button icon="el-icon-question" type="primary" @click.prevent.stop="guide">
      {{ $t('guide.button') }}
    </el-button>
    <div class="test-main">
      <BaseTable :columns="columnObj" :dataList="rows">
        <!-- 操作 -->
        <template #optColumn="{row}">
          <div class="operations">
            <el-button type="primary" size="small" @click="editBtn(row)">编辑</el-button>
            <el-button type="primary" size="small" @click="deleteBtn(row)">删除</el-button>
          </div>
        </template>
      </BaseTable>
    </div>
    <!-- 编辑表单 -->
    <DialogForm ref="formRef" :isFlag="isFlag" :num.sync="newNum" @refreshData="refreshForm"></DialogForm>
    <p style="background-color:pink;width:100%;height:20px;">{{ newNum }}</p>
    <div>
      <el-button type="primary" @click="test">测试</el-button>
      <el-input v-model="formData.name"></el-input>
    </div>
    <div>
      <p>我是父组件</p>
      <div>父组件接收子组件传的值：{{msg}}</div>
    </div>
    <Test v-if="showT" :form="formData" :hasAdd="hasAdd" />
    <Child @getValue="getNum" :fatherNum="msg"></Child>
  </div>
</template>

<script>
import Driver from 'driver.js' // import driver.js
import 'driver.js/dist/driver.min.css' // import driver.js css
import steps from './defineSteps'
import BaseTable from './cmps/baseTable'
import Test from './cmps/test'
import Child from './cmps/child'
import DialogForm from './dialogForm'

export default {
  name: 'Guide',
  components: { BaseTable, Test, Child, DialogForm },
  data() {
    return {
      msg: 0,
      driver: null,
      columnObj: [
        {
          key: 'itemName',
          label: '工程项目名称',
          width: '200'
          // slotName: 'itemName'
        },
        {
          key: 'companyName',
          label: '参建单位/费用类型',
          width: '400'
          // slotName: 'companyName'
        },
        {
          key: 'giveMoney',
          label: '送审金额(元)'
        },
        {
          key: 'firstMoney',
          label: '初审金额(元)'
        },
        {
          key: 'auditMoney',
          label: '审定金额(元)'
        },
        // {
        //   key: 'auditemStatus',
        //   label: '项目状态',
        //   slotName: 'auditemStatus',
        // },
        {
          key: 'optColumn',
          label: '操作',
          slotName: 'optColumn',
          width: '150',
          fixed: 'right'
        }
      ],
      rows: [
        {
          pageEntity: null,
          inputUser: null,
          updateUser: null,
          inputStamp: 1697621793894,
          updateStamp: 1697621793894,
          giveitemId: 565161,
          itemId: "561152",
          cpmisId: null,
          itemCode: "外包费用测试0907",
          itemName: "外包费用测试0907",
          planType: null,
          specialSmallType: null,
          typeId: 0,
          manageLevel: null,
          company: "0099002274",
          companyName: "中国电信股份有限公司智慧家庭运营中心",
          department: null,
          departmentName: null,
          itemSource: "2",
          itemType: null,
          itemUrl: null,
          auditemStatus: "05",
          projectState: "2",
          processinstid: "JS|piid:0d2fa561-5a8c-4dbf-9ca8-e148c0ef6e0f",
          currentlink: "发起人修改",
          currentState: "4",
          currentDate: null,
          auditMethod: "1",
          audUnit: "32",
          audUnitName: null,
          giveMoney: "10000.00",
          firstMoney: "10000.00",
          auditMoney: "2000.00",
          returnBackDate: null,
          returnBackReason: null,
          itemPrincipal: "张明",
          itemPrincipalId: "32051275@JS",
          itemPrincipalUser: null,
          submitTime: "2020-09-07",
          appDate: "2020-09-07",
          auditDate: null,
          closeDate: null,
          pigeonholeDate: null,
          giveNum: null,
          giveAuditTotal: null,
          giveAuditNum: null,
          assignUserId: null,
          assignUserName: null,
          projectArranger: "32051275@JS",
          projectArrangerName: null,
          projectArrangerPhone: null,
          orgMethod: "02",
          itemAuditType: "10",
          ifEntrust: "1",
          outUnitCode: "jstest",
          outUnitName: "江苏测试0001",
          outUnitPerson: "1912418",
          outHtbh: null,
          auditInformNo: null,
          outPrice: "1400.00",
          designreplycode: null,
          designreplysum: null,
          designreplydate: null,
          itemmanId: "32000001424",
          itemmanName: "张明",
          itemman: null,
          startworkdate: null,
          firstacceptdate: null,
          lastacceptdate: null,
          processLog: null,
          itemBasicInfoModel: null,
          giveItemContentModels: [
            {
              pageEntity: null,
              inputUser: null,
              updateUser: null,
              inputStamp: 1697621793894,
              updateStamp: 1697621793894,
              giveItemId: 565161,
              itemCode: "外包费用测试0907",
              cpmisId: null,
              auditCode: "11111111",
              auditName: "广州闻知工程造价咨询有限公司",
              auditType: "3",
              giveMoney: "10000",
              firstMoney: "10000",
              auditMoney: "2000",
              giveMoneyBackup: "10000",
              firstMoneyBackup: "10000",
              auditIdentify: "SGXZ32317",
              giveMoneyFp: "2000",
              firstMoneyFp: "2000",
              auditMoneyFp: "1000",
              giveMoneyFpBackup: null,
              firstMoneyFpBackup: null,
              bedgetid: null,
              entrustmentCode: null,
              entrustmentContent: null,
              framworkCode: null,
              sgdwname: null,
              itemCompanyrefDetail: null,
              giveNumber: null,
              projName: null,
              projCode: null
            }
          ],
          itemOthersModels: null,
          attachmentInfos: null,
          itemVerdictModels: null,
          itemVerdictPrintModels: [{
              pageEntity: null,
              inputUser: null,
              updateUser: null,
              inputStamp: 1697621793894,
              updateStamp: 1697621793894,
              verdictPrintId: "20-JS-0701-000185-DAB01",
              giveitemId: "565161",
              itemCode: "外包费用测试0907",
              itemName: "外包费用测试0907",
              companyId: "0099002274",
              constructId: "11111111",
              constructName: "广州闻知工程造价咨询有限公司",
              constructType: "3",
              giveMoney: "10000",
              firstMoney: "10000",
              auditMoney: "2000",
              constructUser: "张明",
              constructLeader: null,
              builderUser: null,
              builderLeader: null,
              auditer: "张明",
              auditLeader: null,
              operator: "32051275@JS",
              createTime: "2021-06-21",
              submitted: "0",
              flag: "10",
              identifier: null,
              projectId: null,
              constructDate: null,
              builderDate: null,
              auditDate: null,
              sgdwName: null,
              outPersonName: null,
              outAuditDate: null,
              reCheckerName: null,
              reCheckerAccount: null,
              itemVerdictModels: null
          }],
          accountModel: null,
          audittypeCode: "0701",
          projectId: "20-JS-0701-000185",
          typeCodeFk: null,
          giveMoneyBackup: null,
          firstMoneyBackup: null,
          designreplycodeBackup: null,
          designreplysumBackup: null,
          workloadIn: null,
          workloadOut: "1",
          designreplydateBackup: null,
          serialNumber: null,
          reportFile: null,
          serialNumberOut: null,
          reportFileOut: null,
          outTaxRate: null,
          outTax: "79.25",
          outTaxPrice: "1320.75",
          sampleType: "0",
          itemTypeSam: null,
          sampleState: null,
          projectPersonId: "32051275@JS",
          projectPersonName: "张明",
          isRepeat: null,
          isBedget: null,
          siteAuditFlag: null,
          outHtName: null,
          itemVerdictFirstTime: null,
          investmentChannels: null,
          isTax: null,
          isCost: null,
          warningInfoList: [
           "高审减"
          ],
          materialCode: null,
          materialName: null,
          presentName: null,
          presentId: null,
          transferPerson: null,
          accumulatedAmount: null
        },
        {
          pageEntity: null,
          inputUser: null,
          updateUser: null,
          inputStamp: 1697621793894,
          updateStamp: 1697621793894,
          giveitemId: 565161,
          itemId: "561152",
          cpmisId: null,
          itemCode: "外包费用测试0907",
          itemName: "外包费用测试0907",
          planType: null,
          specialSmallType: null,
          typeId: 0,
          manageLevel: null,
          company: "0099002274",
          companyName: "中国电信股份有限公司智慧家庭运营中心",
          department: null,
          departmentName: null,
          itemSource: "2",
          itemType: null,
          itemUrl: null,
          auditemStatus: "05",
          projectState: "2",
          processinstid: "JS|piid:0d2fa561-5a8c-4dbf-9ca8-e148c0ef6e0f",
          currentlink: "发起人修改",
          currentState: "4",
          currentDate: null,
          auditMethod: "1",
          audUnit: "32",
          audUnitName: null,
          giveMoney: "10000.00",
          firstMoney: "10000.00",
          auditMoney: "2000.00",
          returnBackDate: null,
          returnBackReason: null,
          itemPrincipal: "张明",
          itemPrincipalId: "32051275@JS",
          itemPrincipalUser: null,
          submitTime: "2020-09-07",
          appDate: "2020-09-07",
          auditDate: null,
          closeDate: null,
          pigeonholeDate: null,
          giveNum: null,
          giveAuditTotal: null,
          giveAuditNum: null,
          assignUserId: null,
          assignUserName: null,
          projectArranger: "32051275@JS",
          projectArrangerName: null,
          projectArrangerPhone: null,
          orgMethod: "02",
          itemAuditType: "10",
          ifEntrust: "1",
          outUnitCode: "jstest",
          outUnitName: "江苏测试0001",
          outUnitPerson: "1912418",
          outHtbh: null,
          auditInformNo: null,
          outPrice: "1400.00",
          designreplycode: null,
          designreplysum: null,
          designreplydate: null,
          itemmanId: "32000001424",
          itemmanName: "张明",
          itemman: null,
          startworkdate: null,
          firstacceptdate: null,
          lastacceptdate: null,
          processLog: null,
          itemBasicInfoModel: null,
          giveItemContentModels: [
            {
              pageEntity: null,
              inputUser: null,
              updateUser: null,
              inputStamp: 1697621793894,
              updateStamp: 1697621793894,
              giveItemId: 565161,
              itemCode: "外包费用测试0907",
              cpmisId: null,
              auditCode: "11111111",
              auditName: "广州闻知工程造价咨询有限公司",
              auditType: "3",
              giveMoney: "10000",
              firstMoney: "10000",
              auditMoney: "2000",
              giveMoneyBackup: "10000",
              firstMoneyBackup: "10000",
              auditIdentify: "SGXZ32317",
              giveMoneyFp: "2000",
              firstMoneyFp: "2000",
              auditMoneyFp: "1000",
              giveMoneyFpBackup: null,
              firstMoneyFpBackup: null,
              bedgetid: null,
              entrustmentCode: null,
              entrustmentContent: null,
              framworkCode: null,
              sgdwname: null,
              itemCompanyrefDetail: null,
              giveNumber: null,
              projName: null,
              projCode: null
            }
          ],
          itemOthersModels: null,
          attachmentInfos: null,
          itemVerdictModels: null,
          itemVerdictPrintModels: [{
              pageEntity: null,
              inputUser: null,
              updateUser: null,
              inputStamp: 1697621793894,
              updateStamp: 1697621793894,
              verdictPrintId: "20-JS-0701-000185-DAB01",
              giveitemId: "565161",
              itemCode: "外包费用测试0907",
              itemName: "外包费用测试0907",
              companyId: "0099002274",
              constructId: "11111111",
              constructName: "广州闻知工程造价咨询有限公司",
              constructType: "3",
              giveMoney: "10000",
              firstMoney: "10000",
              auditMoney: "2000",
              constructUser: "张明",
              constructLeader: null,
              builderUser: null,
              builderLeader: null,
              auditer: "张明",
              auditLeader: null,
              operator: "32051275@JS",
              createTime: "2021-06-21",
              submitted: "0",
              flag: "10",
              identifier: null,
              projectId: null,
              constructDate: null,
              builderDate: null,
              auditDate: null,
              sgdwName: null,
              outPersonName: null,
              outAuditDate: null,
              reCheckerName: null,
              reCheckerAccount: null,
              itemVerdictModels: null
          }],
          accountModel: null,
          audittypeCode: "0701",
          projectId: "20-JS-0701-000185",
          typeCodeFk: null,
          giveMoneyBackup: null,
          firstMoneyBackup: null,
          designreplycodeBackup: null,
          designreplysumBackup: null,
          workloadIn: null,
          workloadOut: "1",
          designreplydateBackup: null,
          serialNumber: null,
          reportFile: null,
          serialNumberOut: null,
          reportFileOut: null,
          outTaxRate: null,
          outTax: "79.25",
          outTaxPrice: "1320.75",
          sampleType: "0",
          itemTypeSam: null,
          sampleState: null,
          projectPersonId: "32051275@JS",
          projectPersonName: "张明",
          isRepeat: null,
          isBedget: null,
          siteAuditFlag: null,
          outHtName: null,
          itemVerdictFirstTime: null,
          investmentChannels: null,
          isTax: null,
          isCost: null,
          warningInfoList: [
           "高审减"
          ],
          materialCode: null,
          materialName: null,
          presentName: null,
          presentId: null,
          transferPerson: null,
          accumulatedAmount: null
        }
        // {
        //     "pageEntity": null,
        //     "inputUser": null,
        //     "updateUser": null,
        //     "inputStamp": 1697621793894,
        //     "updateStamp": 1697621793894,
        //     "giveitemId": 565104,
        //     "itemId": "561104",
        //     "cpmisId": null,
        //     "itemCode": "现场附件测试0806",
        //     "itemName": "现场附件测试0806",
        //     "planType": null,
        //     "specialSmallType": null,
        //     "typeId": 0,
        //     "manageLevel": null,
        //     "company": "0099002274",
        //     "companyName": "中国电信股份有限公司智慧家庭运营中心",
        //     "department": null,
        //     "departmentName": null,
        //     "itemSource": "2",
        //     "itemType": null,
        //     "itemUrl": null,
        //     "auditemStatus": "05",
        //     "projectState": "2",
        //     "processinstid": "JS|piid:1e334a83-563b-4cfa-ad97-fc36478b15ad",
        //     "currentlink": "发起人修改",
        //     "currentState": "4",
        //     "currentDate": null,
        //     "auditMethod": "1",
        //     "audUnit": "32",
        //     "audUnitName": null,
        //     "giveMoney": "100.00",
        //     "firstMoney": "100.00",
        //     "auditMoney": "80.00",
        //     "returnBackDate": null,
        //     "returnBackReason": null,
        //     "itemPrincipal": "张明",
        //     "itemPrincipalId": "32051275@JS",
        //     "itemPrincipalUser": null,
        //     "submitTime": "2020-08-06",
        //     "appDate": "2020-08-06",
        //     "auditDate": null,
        //     "closeDate": null,
        //     "pigeonholeDate": null,
        //     "giveNum": null,
        //     "giveAuditTotal": null,
        //     "giveAuditNum": null,
        //     "assignUserId": null,
        //     "assignUserName": null,
        //     "projectArranger": "32051275@JS",
        //     "projectArrangerName": null,
        //     "projectArrangerPhone": null,
        //     "orgMethod": "01",
        //     "itemAuditType": "10",
        //     "ifEntrust": "0",
        //     "outUnitCode": null,
        //     "outUnitName": null,
        //     "outUnitPerson": null,
        //     "outHtbh": null,
        //     "auditInformNo": null,
        //     "outPrice": null,
        //     "designreplycode": null,
        //     "designreplysum": null,
        //     "designreplydate": null,
        //     "itemmanId": "32000001424",
        //     "itemmanName": "张明",
        //     "itemman": null,
        //     "startworkdate": null,
        //     "firstacceptdate": null,
        //     "lastacceptdate": null,
        //     "processLog": null,
        //     "itemBasicInfoModel": null,
        //     "giveItemContentModels": [
        //         {
        //             "pageEntity": null,
        //             "inputUser": null,
        //             "updateUser": null,
        //             "inputStamp": 1697621793894,
        //             "updateStamp": 1697621793894,
        //             "giveItemId": 565104,
        //             "itemCode": "现场附件测试0806",
        //             "cpmisId": null,
        //             "auditCode": "11111111",
        //             "auditName": "广州闻知工程造价咨询有限公司",
        //             "auditType": "3",
        //             "giveMoney": "100",
        //             "firstMoney": "100",
        //             "auditMoney": "80",
        //             "giveMoneyBackup": "100",
        //             "firstMoneyBackup": "100",
        //             "auditIdentify": "SGXZ32237",
        //             "giveMoneyFp": "0",
        //             "firstMoneyFp": "0",
        //             "auditMoneyFp": "0",
        //             "giveMoneyFpBackup": null,
        //             "firstMoneyFpBackup": null,
        //             "bedgetid": null,
        //             "entrustmentCode": null,
        //             "entrustmentContent": null,
        //             "framworkCode": null,
        //             "sgdwname": null,
        //             "itemCompanyrefDetail": null,
        //             "giveNumber": null,
        //             "projName": null,
        //             "projCode": null
        //         }
        //     ],
        //     "itemOthersModels": null,
        //     "attachmentInfos": null,
        //     "itemVerdictModels": null,
        //     "itemVerdictPrintModels": [
        //         {
        //             "pageEntity": null,
        //             "inputUser": null,
        //             "updateUser": null,
        //             "inputStamp": 1697621793894,
        //             "updateStamp": 1697621793894,
        //             "verdictPrintId": "20-JS-0701-000158-DAB01",
        //             "giveitemId": "565104",
        //             "itemCode": "现场附件测试0806",
        //             "itemName": "现场附件测试0806",
        //             "companyId": "0099002274",
        //             "constructId": "11111111",
        //             "constructName": "广州闻知工程造价咨询有限公司",
        //             "constructType": "3",
        //             "giveMoney": "100",
        //             "firstMoney": "100",
        //             "auditMoney": "80",
        //             "constructUser": "张明",
        //             "constructLeader": null,
        //             "builderUser": null,
        //             "builderLeader": null,
        //             "auditer": "张明",
        //             "auditLeader": null,
        //             "operator": "32051275@JS",
        //             "createTime": "2020-08-06",
        //             "submitted": "0",
        //             "flag": "10",
        //             "identifier": null,
        //             "projectId": null,
        //             "constructDate": null,
        //             "builderDate": null,
        //             "auditDate": null,
        //             "sgdwName": null,
        //             "outPersonName": null,
        //             "outAuditDate": null,
        //             "reCheckerName": null,
        //             "reCheckerAccount": null,
        //             "itemVerdictModels": null
        //         }
        //     ],
        //     "accountModel": null,
        //     "audittypeCode": "0701",
        //     "projectId": "20-JS-0701-000158",
        //     "typeCodeFk": null,
        //     "giveMoneyBackup": null,
        //     "firstMoneyBackup": null,
        //     "designreplycodeBackup": null,
        //     "designreplysumBackup": null,
        //     "workloadIn": null,
        //     "workloadOut": null,
        //     "designreplydateBackup": null,
        //     "serialNumber": null,
        //     "reportFile": null,
        //     "serialNumberOut": null,
        //     "reportFileOut": null,
        //     "outTaxRate": null,
        //     "outTax": null,
        //     "outTaxPrice": null,
        //     "sampleType": "0",
        //     "itemTypeSam": null,
        //     "sampleState": null,
        //     "projectPersonId": "32051275@JS",
        //     "projectPersonName": "张明",
        //     "isRepeat": null,
        //     "isBedget": null,
        //     "siteAuditFlag": null,
        //     "outHtName": null,
        //     "itemVerdictFirstTime": null,
        //     "investmentChannels": null,
        //     "isTax": null,
        //     "isCost": null,
        //     "warningInfoList": [
        //         "高审减"
        //     ],
        //     "materialCode": null,
        //     "materialName": null,
        //     "presentName": null,
        //     "presentId": null,
        //     "transferPerson": null,
        //     "accumulatedAmount": null
        // },
        // {
        //     "pageEntity": null,
        //     "inputUser": null,
        //     "updateUser": null,
        //     "inputStamp": 1697621793894,
        //     "updateStamp": 1697621793894,
        //     "giveitemId": 565023,
        //     "itemId": "561032",
        //     "cpmisId": null,
        //     "itemCode": "决算测试06150001",
        //     "itemName": "决算测试06150001",
        //     "planType": null,
        //     "specialSmallType": null,
        //     "typeId": 0,
        //     "manageLevel": null,
        //     "company": "32JSDW02",
        //     "companyName": "省公司重点办",
        //     "department": null,
        //     "departmentName": null,
        //     "itemSource": "2",
        //     "itemType": null,
        //     "itemUrl": null,
        //     "auditemStatus": "06",
        //     "projectState": "2",
        //     "processinstid": "JS|piid:a44c339c-1a72-42da-bba5-e95d4b21c350",
        //     "currentlink": "发起人修改",
        //     "currentState": "4",
        //     "currentDate": null,
        //     "auditMethod": "6",
        //     "audUnit": "32",
        //     "audUnitName": null,
        //     "giveMoney": "50.00",
        //     "firstMoney": "40.00",
        //     "auditMoney": "30.00",
        //     "returnBackDate": null,
        //     "returnBackReason": null,
        //     "itemPrincipal": "张明",
        //     "itemPrincipalId": "32051275@JS",
        //     "itemPrincipalUser": null,
        //     "submitTime": "2020-06-15",
        //     "appDate": "2020-06-15",
        //     "auditDate": null,
        //     "closeDate": null,
        //     "pigeonholeDate": null,
        //     "giveNum": null,
        //     "giveAuditTotal": null,
        //     "giveAuditNum": null,
        //     "assignUserId": null,
        //     "assignUserName": null,
        //     "projectArranger": "32051275@JS",
        //     "projectArrangerName": null,
        //     "projectArrangerPhone": null,
        //     "orgMethod": "02",
        //     "itemAuditType": "10",
        //     "ifEntrust": "1",
        //     "outUnitCode": "jstest",
        //     "outUnitName": "江苏测试0001",
        //     "outUnitPerson": "1912418",
        //     "outHtbh": null,
        //     "auditInformNo": null,
        //     "outPrice": "212.00",
        //     "designreplycode": null,
        //     "designreplysum": null,
        //     "designreplydate": null,
        //     "itemmanId": "32000001424",
        //     "itemmanName": "张明",
        //     "itemman": null,
        //     "startworkdate": null,
        //     "firstacceptdate": null,
        //     "lastacceptdate": null,
        //     "processLog": null,
        //     "itemBasicInfoModel": null,
        //     "giveItemContentModels": null,
        //     "itemOthersModels": null,
        //     "attachmentInfos": null,
        //     "itemVerdictModels": null,
        //     "itemVerdictPrintModels": null,
        //     "accountModel": {
        //         "pageEntity": null,
        //         "inputUser": null,
        //         "updateUser": null,
        //         "inputStamp": 1697621793894,
        //         "updateStamp": 1697621793894,
        //         "signId": 13231,
        //         "giveitemId": "565023",
        //         "itemId": "561032",
        //         "itemCode": "决算测试06150001",
        //         "itemName": "决算测试06150001",
        //         "audUnitName": null,
        //         "outReportId": "test001",
        //         "startworkdate": null,
        //         "firstacceptdate": null,
        //         "lastacceptdate": null,
        //         "itemconfirmno": null,
        //         "checkInvest": null,
        //         "giveMoney": "50",
        //         "firstMoney": "40",
        //         "auditMoney": "30",
        //         "operator": "张明",
        //         "createTime": "2020-06-15",
        //         "auditDate": "2021-02-03",
        //         "auditDesc": "undefined\nundefined\nundefined\nundefined",
        //         "auditMind": "同意审计通过;",
        //         "auditedMind": null,
        //         "processinstid": null,
        //         "billState": "1",
        //         "temp": null,
        //         "createflag": "2",
        //         "sendState": null,
        //         "accountDataModels": null,
        //         "accountDetailModels": [
        //             {
        //                 "pageEntity": null,
        //                 "inputUser": null,
        //                 "updateUser": null,
        //                 "inputStamp": 1697621793894,
        //                 "updateStamp": 1697621793894,
        //                 "signDetailId": 21945,
        //                 "signId": "13231",
        //                 "signType": "2",
        //                 "unitId": "05",
        //                 "unitName": "建筑安装工程投资",
        //                 "giveMoney": null,
        //                 "auditMoney": "9",
        //                 "firstMoney": "10",
        //                 "remark": null,
        //                 "accountName": null,
        //                 "design": "10"
        //             },
        //             {
        //                 "pageEntity": null,
        //                 "inputUser": null,
        //                 "updateUser": null,
        //                 "inputStamp": 1697621793894,
        //                 "updateStamp": 1697621793894,
        //                 "signDetailId": 21946,
        //                 "signId": "13231",
        //                 "signType": "2",
        //                 "unitId": "06",
        //                 "unitName": "设备投资",
        //                 "giveMoney": null,
        //                 "auditMoney": "8",
        //                 "firstMoney": "10",
        //                 "remark": null,
        //                 "accountName": null,
        //                 "design": "10"
        //             },
        //             {
        //                 "pageEntity": null,
        //                 "inputUser": null,
        //                 "updateUser": null,
        //                 "inputStamp": 1697621793894,
        //                 "updateStamp": 1697621793894,
        //                 "signDetailId": 21947,
        //                 "signId": "13231",
        //                 "signType": "2",
        //                 "unitId": "07",
        //                 "unitName": "待摊投资",
        //                 "giveMoney": null,
        //                 "auditMoney": "7",
        //                 "firstMoney": "10",
        //                 "remark": null,
        //                 "accountName": null,
        //                 "design": "10"
        //             },
        //             {
        //                 "pageEntity": null,
        //                 "inputUser": null,
        //                 "updateUser": null,
        //                 "inputStamp": 1697621793894,
        //                 "updateStamp": 1697621793894,
        //                 "signDetailId": 21948,
        //                 "signId": "13231",
        //                 "signType": "2",
        //                 "unitId": "08",
        //                 "unitName": "其他投资",
        //                 "giveMoney": null,
        //                 "auditMoney": "6",
        //                 "firstMoney": "10",
        //                 "remark": null,
        //                 "accountName": null,
        //                 "design": "10"
        //             },
        //             {
        //                 "pageEntity": null,
        //                 "inputUser": null,
        //                 "updateUser": null,
        //                 "inputStamp": 1697621793894,
        //                 "updateStamp": 1697621793894,
        //                 "signDetailId": 21949,
        //                 "signId": "13231",
        //                 "signType": "2",
        //                 "unitId": "09",
        //                 "unitName": "预备费",
        //                 "giveMoney": null,
        //                 "auditMoney": null,
        //                 "firstMoney": null,
        //                 "remark": null,
        //                 "accountName": null,
        //                 "design": "10"
        //             }
        //         ],
        //         "submittime": "2020-06-15",
        //         "outUnitName": "江苏测试0001",
        //         "ifEntrust": "1",
        //         "itemSource": "2",
        //         "projectArranger": "32051275@JS",
        //         "itemmanId": "32000001424",
        //         "itemprincipalId": null,
        //         "projectId": "20-JS-0702-000029",
        //         "itemUrl": null,
        //         "auditer": null,
        //         "auditLeader": null
        //     },
        //     "audittypeCode": "0702",
        //     "projectId": "20-JS-0702-000029",
        //     "typeCodeFk": null,
        //     "giveMoneyBackup": null,
        //     "firstMoneyBackup": null,
        //     "designreplycodeBackup": null,
        //     "designreplysumBackup": null,
        //     "workloadIn": null,
        //     "workloadOut": "1",
        //     "designreplydateBackup": null,
        //     "serialNumber": null,
        //     "reportFile": null,
        //     "serialNumberOut": null,
        //     "reportFileOut": null,
        //     "outTaxRate": null,
        //     "outTax": "12.00",
        //     "outTaxPrice": "200.00",
        //     "sampleType": "0",
        //     "itemTypeSam": null,
        //     "sampleState": null,
        //     "projectPersonId": "32051275@JS",
        //     "projectPersonName": "张明",
        //     "isRepeat": null,
        //     "isBedget": null,
        //     "siteAuditFlag": null,
        //     "outHtName": null,
        //     "itemVerdictFirstTime": null,
        //     "investmentChannels": null,
        //     "isTax": null,
        //     "isCost": null,
        //     "warningInfoList": [],
        //     "materialCode": null,
        //     "materialName": null,
        //     "presentName": null,
        //     "presentId": null,
        //     "transferPerson": null,
        //     "accumulatedAmount": null
        // }
      ],
      isFlag: 1,
      newNum: 'world',
      itemName: '',
      showT: false,
      formData: {
        name: '你好，child'
      }
    }
  },
  created() {
    // this.isFlag = 3
    // this.formData.name = '我是created'
    
    // console.log(this.newNum, 'created-father')
    console.log(this.formData.name, 'created-father')
  },
  mounted() {
    this.driver = new Driver()
    this.msg = 100
    // console.log(this.newNum, 'mounted')
    // this.formData.name = '我是mounted'
    console.log(this.formData.name, 'mounted-father')
  },
  updated() {
    // console.log(this.newNum, 'updated')
    // this.formData.name = '我是updated'
    console.log(this.formData.name, 'updated-father')
  },
  methods: {
    guide() {
      this.driver.defineSteps(steps)
      this.driver.start()
    },
    // 获取数据
    getNum(val) {
      this.msg = val
    },
    // 测试
    test() {
      // this.formData.name = '我是test'
      this.showT = true
      console.log(this.showT, 'testtttt')
    },
    hasAdd() {
      this.formData.name = '我是add'
      console.log(this.formData.name + 'hasAdd')
    },
    // 编辑
    editBtn(val) {
      console.log(val, 'editBtn')
      this.$nextTick(() => {
        this.$refs.formRef.init(val)
      })
    },
    // 删除
    deleteBtn(val) {
      console.log(val, 'deleteBtn')
      console.log(this.$refs.formRef.isShow, 'formRef')
      this.$refs.formRef.isShow = true
    },
    // 刷新数据
    refreshForm(val) {
      console.log(val, 'refreshForm0')
      this.itemName = val
      console.log(this.itemName, 'refreshForm1')
    }
  }
}
</script>
<style lang="scss" scoped>
.test-main {
  width:100%;
  margin-top:5px;
  border-top:1px solid #ccc;
}
</style>
